### ISSUE TITLE
Joystick Selection in Pause & Game Over [Bug]

### ISSUE THREAD

**Issue by Junl424** [Twisted-BrainZ/Turtles#7]
Selecting button in Pause or Game Over menu with left joystick seems to move multiple times to left or right, so it is impossible to select the other button (home/play or home/retry). As it moves more than once, the selection comes back to the first button.

(It works fine with controller arrows or keyboard.)

**To Reproduce**
1. Go to Pause menu or Game over menu
2. Try to select with joystick 
3. See error

**Expected behavior**
Normal move selection, 1x move by left or right with joystick

**Comment by Maxwelljones** [comment]
@Junl424 can you try it now? Seems to be sorted :P

**Comment by Maxwelljones** [comment]
Sorted in update 0.3.1
